### ISSUE TITLE
About using segmentation GT of 133 categories

### ISSUE THREAD

**Issue by dqj5182** [sha2nkt/deco#11]
In the paper, it says "We obtain pseudo ground-truth scene segmentation masks, Xs ∈ R H×W×No , containing semantic labels for No = 133 categories". Do you modify the default option of Mask2Former to get 133 categories? If so, what modification do you impose to the base code?

**Comment by dqj5182** [comment]
It seems that the only pretrained model with 133 categories is maskformer2_R50_bs16_50ep.yaml while the other issue, the DECO author mentions that they use maskformer2_swin_large_IN21k_384_bs16_100ep.yaml. May I ask which one was correct?

**Comment by ac5113** [comment]
Please note that since `coco_2017_val_panoptic` has 133 class labels, if inference is performed using one of the panoptic segmentation models, the output would have 133 class labels. This is for all Mask2Former panoptic segmentation models on coco 2017 val panoptic.

You can check these 133 classes by following these steps:
1. Install detectron2
`python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'`
2. `from detectron2.data import MetadataCatalog`
`coco_metadata = MetadataCatalog.get("coco_2017_val_panoptic")`
`print(coco_metadata.stuff_classes)`

Additionally, you can also obtain the corresponding colors using the `stuff_colors` key

**Comment by dqj5182** [comment]
Thanks a lot!
