### ISSUE TITLE
Why does the code split segmentation output with num_parts = 133? (about background processing)

### ISSUE THREAD

**Issue by dqj5182** [sha2nkt/deco#12]
Sorry for too many questions regarding processing segmentation. I just have a one last question.

It seems that the segmentation outputs 133 classes (excluding background). If I include background, then it seems to be more reasonable to split the segmentation output with num_parts = 134. Why did the code split it with num_parts = 133?

![Screen Shot 2023-10-17 at 4 56 04 PM](https://github.com/sha2nkt/deco/assets/56655511/b67ca14d-45d0-47ef-9118-08ce3459c6ff)

**Comment by ac5113** [comment]
The reasoning was that most (if not all) of the background would fall into one of the coco val panoptic classes, since it is afterall a scene segmentation model.
Thus, background class has been included in the part segmentation prediction and mask, since we would need to differentiate between person/non-person.

**Comment by dqj5182** [comment]
Thanks for the reply.

But, the Mask2Former panoptic segmentation model does output background class (0) which is included in the final panoptic segmentation result. How do you process it? Specifically, what value do you impose the background class to be out of the values of 1 ~ 133?

**Comment by ac5113** [comment]
Please check [this issue](https://github.com/facebookresearch/Mask2Former/issues/200).
Mask2Former discards the background class during inference.
Thus, all 133 classes in the output are object classes.
