### ISSUE TITLE
SMPL-X checkpoint

### ISSUE THREAD

**Issue by dqj5182** [sha2nkt/deco#20]
May I ask if there is any SMPL-X checkpoint?

Meaning that the model is trained to predict contact vertices in SMPL-X mesh vertices.

**Comment by sha2nkt** [comment]
DECO predicts contacts on SMPL body vertices but they can be easily converted to SMPL-X following the conversion script [here](https://github.com/sha2nkt/deco?tab=readme-ov-file#converting-damon-contact-labels-to-smpl-x-format-and-back). Since a separate SMPL-X model checkpoint is not required, we do not release one.

**Comment by dqj5182** [comment]
Thanks! Didn't realize there was conversion script in readme. I'll give it a try!
