### ISSUE TITLE
About the raw images and scene masks in the dataset.

### ISSUE THREAD

**Issue by yyvhang** [sha2nkt/deco#6]
Hi, thanks for the open-source dataset. I downloaded the dataset and printed the RGB value of the scene-mask image, the RGB values are the class-id, e.g. (97, 97, 97). But in the base_dataset.py line13, the function 'mask_split', it seems that the GR channels are fixed to 1 and 0, and the B channel is the class-id. Is this a typo, or maybe I misunderstood? Hope to get your help.
And the provided contact annotations include both human-supported and object-supported, is there any way to split them as the paper suggested?
Best.

**Comment by ac5113** [comment]
For both segmentations, the segmentation image files are stored in such a way that all three channels contain the same data: each pixel being the class id. That function then expands that file into a `(n_classes, h, w)` tensor. Since all three channels (RGB) contain the same data, the array was merely sliced.

**Comment by yyvhang** [comment]
> For both segmentations, the segmentation image files are stored in such a way that all three channels contain the same data: each pixel being the class id. That function then expands that file into a `(n_classes, h, w)` tensor. Since all three channels (RGB) contain the same data, the array was merely sliced.

Thks
